### PR TITLE
Add the 2.1.0

### PR DESCRIPTION
**Pull request by xiki-tempula**
Update the meta.yml to add the pyarrow and loguru to dependency

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
@jan-janssen Hi, for the 2.1.0 that I'm about to release. Two new conda dependencies needs to be added.
They are in the `setup.cfg`, but I guess one need to add them manually to this feedstock.

My current plan is to add two new conda dependencies to the previous version. Then when the new version 2.1.0 is release, the first version (build 0) would have the right dependcy. I wonder if you felt that this is the right approach? Thanks.

**Comment by orbeckst** [comment]
@xiki-tempula create the 2.1.0 on alchemlyb first and get it on pypi.

Then we wait for auto-regro-cf bot to make a PR for the new release. We then modify that PR for the 2.1.0 release. Essentially, cf always comes after GitHub release/pypi.

**Review by orbeckst — CHANGES_REQUESTED** [review]
We don't want to add dependencies to the _current_ package.

Instead we add them once the 2.1.0 PR for cf hits.

**Comment by orbeckst** [comment]
The PR by regro-cf bot _should_ not auto-merge, and then we can update deps.

**Comment by xiki-tempula** [comment]
@conda-forge-admin, please rerender

**Comment by xiki-tempula** [comment]
I cannot see a new PR being made, so I modify this PR to accommodate the new 2.1.0 release.

**Review by orbeckst — APPROVED** [review]

**Comment by orbeckst** [comment]
The regro-cf PR sometimes takes a day or so to arrive but this manual one looked good.

If anything needs to be changed then we can just increase the build number.

**Pull request merged**
